import ArrayJS from './Objects/Array';
import ArrayBufferJS from './Objects/ArrayBuffer';
import AtomicsJS from './Objects/Atomics';
import BigIntJS from './Objects/BigInt';
import BigInt64ArrayJS from './Objects/BigInt64Array';
import BigUint64ArrayJS from './Objects/BigUint64Array';
import BooleanJS from './Objects/Boolean';
import DataViewJS from './Objects/DataView';
import DateJS from './Objects/Date';
import decodeURIJS from './Objects/decodeURI';
import decodeURIComponentJS from './Objects/decodeURIComponent';
import encodeURIJS from './Objects/encodeURI';
import encodeURIComponentJS from './Objects/encodeURIComponent';
import ErrorJS from './Objects/Error';
import EvalErrorJS from './Objects/EvalError';
import Float32ArrayJS from './Objects/Float32Array';
import Float64ArrayJS from './Objects/Float64Array';
import FunctionJS from './Objects/Function';
import InfinityJS from './Objects/Infinity';
import Int8ArrayJS from './Objects/Int8Array';
import Int16ArrayJS from './Objects/Int16Array';
import Int32ArrayJS from './Objects/Int32Array';
import IntlJS from './Objects/Intl';
import JSONJS from './Objects/JSON';
import MapJS from './Objects/Map';
import MathJS from './Objects/Math';
import NaNJS from './Objects/NaN';
import NumberJS from './Objects/Number';
import ObjectJS from './Objects/Object';
import PromiseJS from './Objects/Promise';
import ProxyJS from './Objects/Proxy';
import RangeErrorJS from './Objects/RangeError';
import ReferenceErrorJS from './Objects/ReferenceError';
import ReflectJS from './Objects/Reflect';
import RegExpJS from './Objects/RegExp';
import SetJS from './Objects/Set';
import SharedArrayBufferJS from './Objects/SharedArrayBuffer';
import StringJS from './Objects/String';
import SymbolJS from './Objects/Symbol';
import SyntaxErrorJS from './Objects/SyntaxError';
import TypeErrorJS from './Objects/TypeError';
import Uint8ArrayJS from './Objects/Uint8Array';
import Uint8ClampedArrayJS from './Objects/Uint8ClampedArray';
import Uint16ArrayJS from './Objects/Uint16Array';
import Uint32ArrayJS from './Objects/Uint32Array';
import URIErrorJS from './Objects/URIError';
import WeakMapJS from './Objects/WeakMap';
import WeakSetJS from './Objects/WeakSet';
import WebAssemblyJS from './Objects/WebAssembly';

export const Array = ArrayJS;
export const ArrayBuffer = ArrayBufferJS;
export const Atomics = AtomicsJS;
export const BigInt = BigIntJS;
export const BigInt64Array = BigInt64ArrayJS;
export const BigUint64Array = BigUint64ArrayJS;
export const Boolean = BooleanJS;
export const DataView = DataViewJS;
export const Date = DateJS;
export const decodeURI = decodeURIJS;
export const decodeURIComponent = decodeURIComponentJS;
export const encodeURI = encodeURIJS;
export const encodeURIComponent = encodeURIComponentJS;
export const Error = ErrorJS;
export const EvalError = EvalErrorJS;
export const Float32Array = Float32ArrayJS;
export const Float64Array = Float64ArrayJS;
export const Function = FunctionJS;
// eslint-disable-next-line no-shadow-restricted-names
export const Infinity = InfinityJS;
export const Int8Array = Int8ArrayJS;
export const Int16Array = Int16ArrayJS;
export const Int32Array = Int32ArrayJS;
export const Intl = IntlJS;
export const JSON = JSONJS;
export const Map = MapJS;
export const Math = MathJS;
// eslint-disable-next-line no-shadow-restricted-names
export const NaN = NaNJS;
export const Number = NumberJS;
export const Object = ObjectJS;
export const Promise = PromiseJS;
export const Proxy = ProxyJS;
export const RangeError = RangeErrorJS;
export const ReferenceError = ReferenceErrorJS;
export const Reflect = ReflectJS;
export const RegExp = RegExpJS;
export const Set = SetJS;
export const SharedArrayBuffer = SharedArrayBufferJS;
export const String = StringJS;
export const Symbol = SymbolJS;
export const SyntaxError = SyntaxErrorJS;
export const TypeError = TypeErrorJS;
export const Uint8Array = Uint8ArrayJS;
export const Uint8ClampedArray = Uint8ClampedArrayJS;
export const Uint16Array = Uint16ArrayJS;
export const Uint32Array = Uint32ArrayJS;
export const URIError = URIErrorJS;
export const WeakMap = WeakMapJS;
export const WeakSet = WeakSetJS;
export const WebAssembly = WebAssemblyJS;
